name: Deploy

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  NugetDeploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Source/Source.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        PACKAGE_NAME: Surrogate
