name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - run: |
        ls
        cd ./Source
        ls
    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: cd ../Test
    - run: dotnet test --no-restore --verbosity normal
