name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restoring
      run: |
        cd Source
        dotnet restore
    - name: Building
      run: |
        cd Source
        dotnet build --configuration Release --no-restore
    - name: Testing
      run: |
        cd Test
        dotnet test --no-restore --verbosity normal
