
name: Test

on:
  push:
    branches: '*'

jobs:
  DotnetCoreTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Testing
      run: |
        cd Test
        dotnet test
